variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Towards-AzurePortalServiceConnectionName'
    appType: 'webAppLinux'
    appName: 'webcalculator-app1'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'